version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "podcasts"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ucfm6gwz2pmz"
s3_prefix = "podcasts"
region = "eu-north-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
